# Generated by Django 5.0.2 on 2024-02-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
