# Generated by Django 5.0.2 on 2024-02-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
